name: Backend Branch Workflow

on:
  workflow_dispatch:
    branches:
      - backend
  push:
    branches:
      - backend
  pull_request:
    branches:
      - backend

env:
  HEROKU_API_KEY: ${{ secrets.HEROKU_API_KEY }}
  HEROKU_APP: flatdragon-portfolio-backend

jobs:
  deploy-to-heroku:
    name: Deploy to Heroku
    runs-on: ubuntu-20.04
    steps:

      - name: Checkout Backend Sources
        uses: actions/checkout@v2

      - name: Install Dependencies
        run: composer install --no-ansi --no-interaction --no-scripts --no-progress --prefer-dist

      - name: Get Heroku App Env Variables
        run: |
          heroku container:login
          export APP_KEY=$(heroku config:get APP_KEY)
          export APP_URL=$(heroku apps:info --shell | grep web_url | cut -d= -f2)
          export DATABASE_URL=$(heroku config:get HEROKU_POSTGRESQL)

      - name: Print Current Heroku Env
        run: printenv
