name: Heroku Backend

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

defaults:
  run:
    working-directory: ./backend

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2
      
      - name: Install Dependencies
        run: composer install --no-ansi --no-interaction --no-scripts --no-progress --prefer-dist

      - name: Login to Heroku
        env: 
          HEROKU_API_KEY: ${{ secrets.HEROKU_API_KEY }}
        run: heroku container:login
      
      - name: Set Heroku Env Variables
        run: heroku config:set $(egrep -v '^#' .env.heroku | xargs) --app=${{ secrets.HEROKU_APP_NAME }}
      
      - name: Set Heroku App Key Variable
        run: heroku config:set APP_KEY=$(php artisan key:generate --show)

      - name: Set Heroku App URL Variable
        run: heroku config:set APP_URL=$(heroku apps:info --app=${{ secrets.HEROKU_APP_NAME }} --shell | grep web_url | cut -d= -f2)

      - name: Set Heroku Database URL Variable
        run: heroku config:set DATABASE_URL=$(heroku config:get HEROKU_POSTGRESQL --app=${{ secrets.HEROKU_APP_NAME }})
      
      - name: Deploy Backend Directory
        uses: s0/git-publish-subdir-action@develop
        env:
          REPO: self
          BRANCH: heroku-backend
          FOLDER: ./
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
