name: Main Branch Workflow

on:
  workflow_dispatch:
  push:
    branches:
      - main
  pull_request:
    branches: 
      - main

jobs:
  extract-backend:
    name: Extract Backend Sources
    runs-on: ubuntu-20.04
    steps:

      - name: Checkout Main Branch
        uses: actions/checkout@v2
        with:
          ref: main
          path: main

      - name: Create Backend Branch
        run: |
          cd main
          git fetch --all
          echo "$(git branch --list origin/backend)"
