name: Extract Sources

on:
  push:
    branches:
      - main
  pull_request:
    branches: 
      - main

jobs:
  prepare-branches:
    name: Prepare Branches
    runs-on: ubuntu-20.04
    steps:

      - name: Checkout Main Sources
        uses: actions/checkout@v2
        run: |
          git config user.name github-actions
          git config user.email github-actions@github.com
          git rm -rf .

      - name: Create Backend Branch
        run: |
          git checkout --orphan backend
          git commit --allow-empty -m "init branch"
          git push origin backend

      - name: Create Frontend Branch
        run: |
          git checkout --orphan frontend
          git commit --allow-empty -m "init branch"
          git push origin frontend

  extract-backend:
    name: Extract Backend Sources
    runs-on: ubuntu-20.04
    needs:
      - prepare-branches
    steps:

      - name: Checkout Main Sources
        uses: actions/checkout@v2
        with:
          ref: main
          path: main

      - name: Checkout Backend Sources
        uses: actions/checkout@v2
        with:
          ref: backend
          path: backend
          token: ${{ secrets.PERSONAL_ACCESS_TOKEN }}

      - name: Check
        run: cd backend && ls

      - name: Push Backend Sources to Backend Branch
        run: |
          export GITHUB_SHORT_SHA=$(echo "${{ github.sha }}" | cut -c1-6)
          cp -rf main/backend backend
          cd backend
          git config user.name github-actions
          git config user.email github-actions@github.com
          git add .
          git commit -m "extract backend sources from ${GITHUB_SHORT_SHA}"
          git push
