name: Main Branch Workflow

on:
  workflow_dispatch:
  push:
    branches:
      - main
  pull_request:
    branches: 
      - main

jobs:
  extract-backend:
    name: Extract Backend Sources
    runs-on: ubuntu-20.04
    steps:

      - name: Checkout Main Branch
        uses: actions/checkout@v2
        with:
          ref: main
          path: main

      - name: Create Backend Branch (Conditionally)
        run: |
          cd main
          if [ -z "$(git ls-remote --heads origin backend)" ]
          then
            echo "Backend branch doesn't exists. Starting create..."
            git switch --orphan backend
            git config user.name github-actions
            git config user.email github-actions@github.com
            git commit --allow-empty -m "init backend branch"
            git push origin backend
            git switch main
          else
            echo "Backend branch already exists. Skipping step..."
          fi

      - name: Checkout Backend Branch
        uses: actions/checkout@v2
        with:
          ref: backend
          path: backend
          token: ${{ secrets.PERSONAL_ACCESS_TOKEN }}

      - name: Update Backend Branch (Conditionally)
        run: |
          cd backend
          git pull --ff-only origin backend
          cp -a ../main/backend/. .
          git status --porcelain
          if [ -z "$(git status --porcelain)" ]
          then
            echo "Backend branch is up to date. Skipping step..."
          else
            echo "Backend branch has changes. Starting update..."
            export GITHUB_SHORT_SHA=$(echo "${{ github.sha }}" | cut -c1-7)
            git add .
            git config user.name github-actions
            git config user.email github-actions@github.com
            git commit -m "extract backend sources from ${GITHUB_SHORT_SHA}"
            git push origin backend
          fi   
