name: Extract Sources

on:
  push:
    branches:
      - main
  pull_request:
    branches: 
      - main

jobs:
  extract-backend:
    name: Extract Backend Sources
    runs-on: ubuntu-20.04
    steps:

      - name: Checkout Main Sources
        uses: actions/checkout@v2
        with:
          path: main

      - name: Checkout Backend Sources
        uses: actions/checkout@v2
        with:
          path: backend
          token: ${{ secrets.PERSONAL_ACCESS_TOKEN }}

      - name: Test
        run: |
          cd backend && ls
