name: Main Branch Workflow

on:
  workflow_dispatch:
  push:
    branches:
      - main
  pull_request:
    branches: 
      - main

jobs:
  extract-backend:
    name: Extract Backend Sources
    runs-on: ubuntu-20.04
    steps:

      - name: Checkout Main Branch
        uses: actions/checkout@v2
        with:
          ref: main
          path: main

      - name: Test
        id: check-backend-branch-existence
        run: echo [ -z "$(cd main && git ls-remote --heads origin backend)" ]

      - name: Check Backend Branch Existence
        id: check-backend-branch-existence
        run: echo "::set-output name=is-exists::$([ -z "$(cd main && git ls-remote --heads origin backend)" ])"

      - name: Create Backend Branch
        if: steps.check-backend-branch-existence.outputs.is-exists
        run: |
          echo "NOT EXISTS"
          
