name: Main Branch Workflow

on:
  workflow_dispatch:
  push:
    branches:
      - main
  pull_request:
    branches: 
      - main

jobs:
  extract-backend:
    name: Extract Backend Sources
    runs-on: ubuntu-20.04
    steps:

      - name: Checkout Main Branch
        uses: actions/checkout@v2
        with:
          ref: main
          path: main

      - name: Create Backend Branch
        if: steps.check-backend-branch-existence.outputs.is-exists
        run: |
          cd main
          if [ -z "$(&& git ls-remote --heads origin backend)" ]
          then
            echo "Backend branch doesn't exists. Starting creation..."
            git switch --orphan backend
            git config user.name github-actions
            git config user.email github-actions@github.com
            git commit --allow-empty -m "init backend branch"
            git push origin backend
            git switch main
          else
            echo "Backend branch already exists. Skipping step..."
          fi
