name: Main Workflow

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

env:
  HEROKU_API_KEY: ${{ secrets.HEROKU_API_KEY }}

jobs:

  deploy-backend-app:
    name: Deploy Backend App
    runs-on: ubuntu-20.04
    env:
      HEROKU_APP: ${{ secrets.HEROKU_BACKEND_APP }}
    steps:

      - name: Checkout Main Branch
        uses: actions/checkout@v2

      - name: Get Heroku App Env Variables
        run: |
          heroku container:login
          APP_KEY=$(heroku config:get APP_KEY)
          APP_URL=$(heroku apps:info --shell | grep web_url | cut -d= -f2)
          DATABASE_URL=$(heroku config:get HEROKU_POSTGRESQL)
          echo $APP_KEY
      
      - name: Print Current Heroku Env
        run: echo $APP_KEY
