name: Extract Sources

on:
  push:
    branches:
      - main
  pull_request:
    branches: 
      - main

jobs:
  extract-backend:
    name: Extract Backend Sources
    runs-on: ubuntu-20.04
    steps:

      - name: Checkout Main Branch
        uses: actions/checkout@v2
        with:
          path: main

      - name: Checkout Backend Branch
        uses: actions/checkout@v2
        with:
          path: backend
          token: ${{ secrets.PERSONAL_ACCESS_TOKEN }}

      - name: Update Backend Branch
        run: |
          cd backend
          if [ `git branch --list backend` ]; then git switch backend && git pull origin backend; else git switch --orphan backend; fi
          cp -a ../main/backend/. .
          export GITHUB_SHORT_SHA=$(echo "${{ github.sha }}" | cut -c1-7)
          git config user.name github-actions
          git config user.email github-actions@github.com
          git add .
          git commit -m "extract backend sources from ${GITHUB_SHORT_SHA}"
          git push origin backend
