name: Extract Backend

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  extract:
    name: Extract Backend Sources
    runs-on: ubuntu-20.04
    steps:

      - name: Checkout Repository Sources
        uses: actions/checkout@v2
        
      - name: Create Target Branch If Not Exists
        run: git switch -c backend

      - name: Push Backend Sources to Target Branch
        uses: s0/git-publish-subdir-action@v2.4.0
        env:
          REPO: self
          BRANCH: backend
          FOLDER: backend
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
