name: Extract Sources

on:
  push:
    branches:
      - main
  pull_request:
    branches: 
      - main

jobs:
  extract-backend:
    name: Extract Backend Sources
    runs-on: ubuntu-20.04
    steps:

      - name: Setup GitHub Actions as Git User
        run: |
          git config --global user.name github-actions
          git config --global user.email github-actions@github.com

      - name: Checkout Main Branch
        uses: actions/checkout@v2
        with:
          ref: main
          path: main

      - name: Create Backend Branch
        run: |
          cd main
          if ! [ `git branch --list backend` ]
          then
            git switch --orphan backend
            git commit --allow-empty -m "init backend branch"
            git switch main
          fi
          cd ..

      - name: Checkout Backend Branch
        uses: actions/checkout@v2
        with:
          ref: backend
          path: backend
          token: ${{ secrets.PERSONAL_ACCESS_TOKEN }}

      - name: Update Backend Branch
        run: |
          cd backend
          git pull --ff-only origin backend
          cp -a ../main/backend/. .
          export GITHUB_SHORT_SHA=$(echo "${{ github.sha }}" | cut -c1-7)
          git add .
          git commit -m "extract backend sources from ${GITHUB_SHORT_SHA}"
          git push origin backend
          cd ..
          
