name: Extract Sources

on:
  push:
    branches:
      - main
  pull_request:
    branches: 
      - main

jobs:
  extract-backend:
    name: Extract Backend Sources
    runs-on: ubuntu-20.04
    steps:

      - name: Checkout Main Branch
        uses: actions/checkout@v2
        with:
          path: main

      - name: Checkout Backend Branch
        uses: actions/checkout@v2
        with:
          path: backend
          token: ${{ secrets.PERSONAL_ACCESS_TOKEN }}

      - name: Prepare Backend Branch before Update
        run: |
          cd backend
          git switch -c backend
          git rm -r *
          cp -rf ../main/backend/* .

      - name: Test
        run: cat .env.heroku   
